service: bmt-media-shop-service-refactor

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  profile: serverless-profile


  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::*"
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource: "*"

  environment:
    BUCKET: ${self:service}-templates
    PDF_BUCKET: ${self:service}-pdf
    REVIEWS_TABLE: ${self:service}-table-review
    PROMOCODE_TABLE: ${self:service}-promocode
    USERS_TABLE: ${self:service}-users
    ORDERS_TABLE: ${self:service}-orders

package:
  include:
    - wkhtmltopdf

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
  s3:
    port: 8800
    directory: /tmp
    cors: true

functions:
  auth:
    handler: api/auth/handler.auth

# ================== Invoices =====================

  printInvoice:
    handler: api/invoice/handler.print
    events:
      - http:
          path: invoice/print/{id}
          method: get
          integration: lambda
          cors: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
              Content-Type: "'application/json'"
            template: $input.json('$')

# ================== Promocodes =====================

  createPromocode:
    handler: api/promocode/handler.create
    events:
      - http:
          path: promocode/{userId}
          method: post
          integration: lambda
          cors: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
              Content-Type: "'application/json'"
            template: $input.json('$')


  checkPromocode:
      handler: api/promocode/handler.check
      events:
        - http:
            path: promocode/{userId}
            method: put
            integration: lambda
            cors: true
            authorizer:
              name: auth
              resultTtlInSeconds: 0
            response:
              headers:
                Access-Control-Allow-Origin: "'*'"
                Content-Type: "'application/json'"
              template: $input.json('$')

  getPromocode:
      handler: api/promocode/handler.get
      events:
        - http:
            path: promocode/{userId}
            method: get
            integration: lambda
            cors: true
            authorizer:
              name: auth
              resultTtlInSeconds: 0
            response:
              headers:
                Access-Control-Allow-Origin: "'*'"
                Content-Type: "'application/json'"
              template: $input.json('$')

  removePromocode:
    handler: api/promocode/handler.remove
    events:
      - http:
          path: promocode/{userId}
          method: delete
          integration: lambda
          cors: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
              Content-Type: "'application/json'"
            template: $input.json('$')

# ================== Profiles =====================

  getAllItems:
    handler: api/auth/handler.getAll
    events:
      - http:
          path: api/profiles
          method: get
          integration: lambda
          cors: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
              Content-Type: "'application/json'"
            template: $input.json('$')

  getProfile:
    handler: api/auth/handler.findOrCreate
    events:
      - http:
          path: api/profile
          method: post
          integration: lambda
          cors: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
              Content-Type: "'application/json'"
            template: $input.json('$')

  updateProfile:
    handler: api/auth/handler.update
    events:
      - http:
          method: put
          path: api/profile/{id}
          cors: true
          integration: lambda
          authorizer:
            name: auth
            resultTtlInSeconds: 0
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
              Content-Type: "'application/json'"
            template: $input.json('$')

# ================== Review =====================

  addReview:
    handler: api/review/handler.add
    events:
      - http:
          path: review
          method: post
          integration: lambda
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
              Content-Type: "'application/json'"
            template: $input.json('$')

  getReviews:
      handler: api/review/handler.getByProductID
      events:
        - http:
            path: review/{productID}
            method: get
            integration: lambda
            cors: true
            response:
              headers:
                Access-Control-Allow-Origin: "'*'"
                Content-Type: "'application/json'"
              template: $input.json('$')

# ================== Orders =====================

  createOrder:
    handler: api/order/handler.createOrder
    events:
      - http:
          method: post
          path: api/order
          cors: true
          integration: lambda
          authorizer:
            name: auth
            resultTtlInSeconds: 0
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
              Content-Type: "'application/json'"
            template: $input.json('$')

  getByProfileId:
      handler: api/order/handler.getByProfileId
      events:
        - http:
            method: get
            path: api/order/getByProfileId/{id}
            cors: true
            integration: lambda
            authorizer:
              name: auth
              resultTtlInSeconds: 0
            response:
              headers:
                Access-Control-Allow-Origin: "'*'"
                Content-Type: "'application/json'"
              template: $input.json('$')

  getById:
      handler: api/order/handler.getById
      events:
        - http:
            method: get
            path: api/order/getById/{id}
            cors: true
            integration: lambda
            authorizer:
              name: auth
              resultTtlInSeconds: 0
            response:
              headers:
                Access-Control-Allow-Origin: "'*'"
                Content-Type: "'application/json'"
              template: $input.json('$')

  getByRangeDates:
    handler: api/order/handler.getByRangeDates
    events:
      - http:
          path: api/order/getByRangeDates
          method: get
          integration: lambda
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
              Content-Type: "'application/json'"
            template: $input.json('$')

resources:
  Resources:
    PdfBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.PDF_BUCKET}
    TemplatesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET}
    PromocodeDynamoDb:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TableName: ${self:provider.environment.PROMOCODE_TABLE}

    UsersDynamoDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    ReviewsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.REVIEWS_TABLE}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    OrdersDynamoDb:
          Type: AWS::DynamoDB::Table
          DeletionPolicy: Retain
          Properties:
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            StreamSpecification:
              StreamViewType: NEW_AND_OLD_IMAGES
            TableName: ${self:provider.environment.ORDERS_TABLE}
plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline